/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 20:13:14 GMT 2017
 */

package ru.innopolis.lips.memvit.model;

import org.junit.Test;
import static org.junit.Assert.*;
import org.eclipse.cdt.debug.core.cdi.model.ICDIThread;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ru.innopolis.lips.memvit.model.Model;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Model_ESTest extends Model_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Model model0 = new Model();
      assertFalse(model0.isStateManagementButtonsEnabled());
      
      model0.setStateManagementButtonsEnabled(true);
      boolean boolean0 = model0.isStateManagementButtonsEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Model model0 = new Model();
      model0.setTempDuplicatedStates((-1556));
      int int0 = model0.getDuplicatedStates();
      assertEquals((-1556), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Model model0 = new Model();
      model0.setTempDuplicatedStates(200);
      int int0 = model0.getDuplicatedStates();
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Model model0 = new Model();
      model0.setCurrentThread((ICDIThread) null);
      assertFalse(model0.isUpdatedThread());
      assertEquals(0, model0.getDuplicatedStates());
      assertFalse(model0.isStateManagementButtonsEnabled());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Model model0 = new Model();
      model0.getCurrentThread();
      assertFalse(model0.isStateManagementButtonsEnabled());
      assertEquals(0, model0.getDuplicatedStates());
      assertFalse(model0.isUpdatedThread());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Model model0 = new Model();
      int int0 = model0.getDuplicatedStates();
      assertFalse(model0.isUpdatedThread());
      assertEquals(0, int0);
      assertFalse(model0.isStateManagementButtonsEnabled());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Model model0 = new Model();
      boolean boolean0 = model0.isStateManagementButtonsEnabled();
      assertFalse(model0.isUpdatedThread());
      assertFalse(boolean0);
      assertEquals(0, model0.getDuplicatedStates());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Model model0 = new Model();
      boolean boolean0 = model0.isUpdatedThread();
      assertFalse(boolean0);
      assertFalse(model0.isStateManagementButtonsEnabled());
      assertEquals(0, model0.getDuplicatedStates());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Model model0 = new Model();
      assertFalse(model0.isUpdatedThread());
      
      model0.setUpdatedThread(true);
      boolean boolean0 = model0.isUpdatedThread();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Model model0 = new Model();
      model0.getStateStorage();
      assertFalse(model0.isUpdatedThread());
      assertEquals(0, model0.getDuplicatedStates());
      assertFalse(model0.isStateManagementButtonsEnabled());
  }
}
