/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 20:08:24 GMT 2017
 */

package ru.innopolis.lips.memvit.view;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ru.innopolis.lips.memvit.view.BrowserView;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BrowserView_ESTest extends BrowserView_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BrowserView browserView0 = null;
      try {
        browserView0 = new BrowserView();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/eclipse/core/runtime/preferences/IScopeContext
         //
         assertThrownBy("ru.innopolis.lips.memvit.view.BrowserView", e);
      }
  }
}
