/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 20:09:31 GMT 2017
 */

package ru.innopolis.lips.memvit.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.cdt.debug.core.cdi.event.ICDIEvent;
import org.eclipse.cdt.debug.core.cdi.model.ICDIObject;
import org.eclipse.cdt.debug.mi.core.cdi.Session;
import org.eclipse.cdt.debug.mi.core.cdi.event.CreatedEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ru.innopolis.lips.memvit.controller.DebugEventsListener;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DebugEventsListener_ESTest extends DebugEventsListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DebugEventsListener debugEventsListener0 = new DebugEventsListener();
      // Undeclared exception!
      try { 
        debugEventsListener0.handleDebugEvents((ICDIEvent[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("ru.innopolis.lips.memvit.controller.DebugEventsListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ICDIEvent[] iCDIEventArray0 = new ICDIEvent[0];
      DebugEventsListener debugEventsListener0 = new DebugEventsListener();
      debugEventsListener0.handleDebugEvents(iCDIEventArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DebugEventsListener debugEventsListener0 = new DebugEventsListener();
      ICDIEvent[] iCDIEventArray0 = new ICDIEvent[1];
      CreatedEvent createdEvent0 = new CreatedEvent((Session) null, (ICDIObject) null);
      iCDIEventArray0[0] = (ICDIEvent) createdEvent0;
      // Undeclared exception!
      try { 
        debugEventsListener0.handleDebugEvents(iCDIEventArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/eclipse/core/runtime/preferences/IScopeContext
         //
         assertThrownBy("ru.innopolis.lips.memvit.controller.DebugEventsListener", e);
      }
  }
}
