/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 20:14:07 GMT 2017
 */

package ru.innopolis.lips.memvit.model;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ru.innopolis.lips.memvit.model.ActivationRecord;
import ru.innopolis.lips.memvit.model.VarDescription;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ActivationRecord_ESTest extends ActivationRecord_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord("a/b'Q", (String) null, "a/b'Q", "wNFK.u!fpJX9?slEA", (String) null, varDescriptionArray0, (VarDescription[]) null);
      assertEquals("wNFK.u!fpJX9?slEA", activationRecord0.getStartAddress());
      assertEquals("a/b'Q", activationRecord0.getFileName());
      assertEquals("a/b'Q", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ActivationRecord activationRecord0 = new ActivationRecord("", "<", "", "", "", (VarDescription[]) null, (VarDescription[]) null);
      activationRecord0.getVars();
      assertEquals("", activationRecord0.getFileName());
      assertEquals("", activationRecord0.getStartAddress());
      assertEquals("", activationRecord0.getLineNumber());
      assertEquals("<", activationRecord0.getFunctionName());
      assertEquals("", activationRecord0.getEndAddress());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord((String) null, (String) null, "", "(|:?=wm$6vB)SQ", "", varDescriptionArray0, varDescriptionArray0);
      activationRecord0.getVars();
      assertEquals("", activationRecord0.getFileName());
      assertEquals("(|:?=wm$6vB)SQ", activationRecord0.getStartAddress());
      assertEquals("", activationRecord0.getEndAddress());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ActivationRecord activationRecord0 = new ActivationRecord("", "<", "", "", "", (VarDescription[]) null, (VarDescription[]) null);
      activationRecord0.setStaticLink("");
      activationRecord0.getStaticLink();
      assertEquals("", activationRecord0.getEndAddress());
      assertEquals("", activationRecord0.getFileName());
      assertEquals("", activationRecord0.getLineNumber());
      assertEquals("", activationRecord0.getStartAddress());
      assertEquals("<", activationRecord0.getFunctionName());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord((String) null, (String) null, "", "(|:?=wm$6vB)SQ", "", varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getStartAddress();
      assertEquals("", activationRecord0.getEndAddress());
      assertEquals("", activationRecord0.getFileName());
      assertEquals("(|:?=wm$6vB)SQ", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord("<", "", "", "<", (String) null, varDescriptionArray0, varDescriptionArray0);
      assertEquals("<", activationRecord0.getStartAddress());
      
      activationRecord0.setStartAddress("");
      activationRecord0.getStartAddress();
      assertEquals("", activationRecord0.getFunctionName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
      
      activationRecord0.setLineNumber((String) null);
      activationRecord0.getLineNumber();
      assertEquals("xyz", activationRecord0.getFileName());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord("n6p*+S", "n6p*+S", "n6p*+S", "", "n6p*+S", varDescriptionArray0, varDescriptionArray0);
      assertEquals("n6p*+S", activationRecord0.getLineNumber());
      
      activationRecord0.setLineNumber("");
      activationRecord0.getLineNumber();
      assertEquals("n6p*+S", activationRecord0.getFileName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord((String) null, (String) null, "", "", "", varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getFunctionName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord("<", "", "", "<", (String) null, varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getFileName();
      assertEquals("", string0);
      assertEquals("<", activationRecord0.getStartAddress());
      assertNotNull(string0);
      assertEquals("", activationRecord0.getFunctionName());
      assertEquals("<", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord("&amp;", "&amp;", "", "", "yq~A71kD,ui", varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getEndAddress();
      assertEquals("", activationRecord0.getFileName());
      assertEquals("yq~A71kD,ui", string0);
      assertEquals("&amp;", activationRecord0.getLineNumber());
      assertEquals("", activationRecord0.getStartAddress());
      assertEquals("&amp;", activationRecord0.getFunctionName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord((String) null, (String) null, "", "(|:?=wm$6vB)SQ", "", varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getEndAddress();
      assertEquals("", activationRecord0.getFileName());
      assertEquals("", string0);
      assertEquals("(|:?=wm$6vB)SQ", activationRecord0.getStartAddress());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ActivationRecord activationRecord0 = new ActivationRecord("q)J)\"],rFJ,$RXA", "q)J)\"],rFJ,$RXA", "q)J)\"],rFJ,$RXA", "i&rOvjLSmR", "", (VarDescription[]) null, (VarDescription[]) null);
      activationRecord0.getArgs();
      assertEquals("q)J)\"],rFJ,$RXA", activationRecord0.getFunctionName());
      assertEquals("", activationRecord0.getEndAddress());
      assertEquals("i&rOvjLSmR", activationRecord0.getStartAddress());
      assertEquals("q)J)\"],rFJ,$RXA", activationRecord0.getFileName());
      assertEquals("q)J)\"],rFJ,$RXA", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[0];
      ActivationRecord activationRecord0 = new ActivationRecord("&amp;", "&amp;", "", "", "yq~A71kD,ui", varDescriptionArray0, varDescriptionArray0);
      activationRecord0.getArgs();
      assertEquals("&amp;", activationRecord0.getFunctionName());
      assertEquals("&amp;", activationRecord0.getLineNumber());
      assertEquals("", activationRecord0.getStartAddress());
      assertEquals("yq~A71kD,ui", activationRecord0.getEndAddress());
      assertEquals("", activationRecord0.getFileName());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      activationRecord0.getArgs();
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
      assertEquals("xyz", activationRecord0.getFileName());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getFileName();
      assertEquals("xyz", string0);
      assertNotNull(string0);
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      activationRecord0.setArgs(varDescriptionArray0);
      assertEquals("xyz", activationRecord0.getFileName());
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("", "", "", (String) null, "", varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getStaticLink();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("", "", "", (String) null, "", varDescriptionArray0, varDescriptionArray0);
      activationRecord0.setFileName((String) null);
      String string0 = activationRecord0.getFileName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("", "", "", (String) null, "", varDescriptionArray0, varDescriptionArray0);
      VarDescription[] varDescriptionArray1 = activationRecord0.getVars();
      assertSame(varDescriptionArray1, varDescriptionArray0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      activationRecord0.setVars(varDescriptionArray0);
      assertEquals("xyz", activationRecord0.getFileName());
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      activationRecord0.setStaticLink(" 7GzUZX%|F\">r&");
      activationRecord0.getStaticLink();
      assertEquals("xyz", activationRecord0.getFileName());
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("", "", "", (String) null, "", varDescriptionArray0, varDescriptionArray0);
      activationRecord0.setEndAddress((String) null);
      assertNull(activationRecord0.getEndAddress());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getEndAddress();
      assertEquals("xyz", activationRecord0.getFileName());
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getLineNumber();
      assertEquals("xK4 %`C+A+KEqjl4-", string0);
      assertEquals("xyz", activationRecord0.getFileName());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("xK4 %`C+A+KEqjl4-", (String) null, "xyz", (String) null, (String) null, varDescriptionArray0, varDescriptionArray0);
      activationRecord0.setFunctionName("%;$");
      activationRecord0.getFunctionName();
      assertEquals("xyz", activationRecord0.getFileName());
      assertEquals("xK4 %`C+A+KEqjl4-", activationRecord0.getLineNumber());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ActivationRecord activationRecord0 = new ActivationRecord((String) null, (String) null, "", (String) null, "", (VarDescription[]) null, (VarDescription[]) null);
      String string0 = activationRecord0.getStartAddress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      VarDescription[] varDescriptionArray0 = new VarDescription[1];
      ActivationRecord activationRecord0 = new ActivationRecord("", "", "", (String) null, "", varDescriptionArray0, varDescriptionArray0);
      String string0 = activationRecord0.getFunctionName();
      assertEquals("", string0);
  }
}
