/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 20:13:46 GMT 2017
 */

package ru.innopolis.lips.memvit.model;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ru.innopolis.lips.memvit.model.StateImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StateImpl_ESTest extends StateImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StateImpl stateImpl0 = new StateImpl("");
      stateImpl0.setData((String) null);
      String string0 = stateImpl0.getData();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StateImpl stateImpl0 = new StateImpl("");
      String string0 = stateImpl0.getData();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StateImpl stateImpl0 = new StateImpl("");
      stateImpl0.setData("!iK#h#23");
      String string0 = stateImpl0.getData();
      assertEquals("!iK#h#23", string0);
  }
}
