/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 02 21:23:01 GMT 2017
 */

package ru.innopolis.lips.memvit.model;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import ru.innopolis.lips.memvit.model.StateImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StateImpl_ESTest extends StateImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StateImpl stateImpl0 = new StateImpl((String) null);
      stateImpl0.setData("1g]hM@SeA1");
      String string0 = stateImpl0.getData();
      assertEquals("1g]hM@SeA1", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StateImpl stateImpl0 = new StateImpl("W#]7U`$<8M");
      stateImpl0.setData("");
      String string0 = stateImpl0.getData();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StateImpl stateImpl0 = new StateImpl((String) null);
      String string0 = stateImpl0.getData();
      assertNull(string0);
  }
}
