/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Apr 10 20:05:30 GMT 2017
 */

package ru.innopolis.lips.memvit.controller;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@SuppressWarnings("unused")
@EvoSuiteClassExclude
public class Controller_ESTest_scaffolding {

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "ru.innopolis.lips.memvit.controller.Controller"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init(); 
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("java.vm.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.specification.version", "1.8"); 
            java.lang.System.setProperty("java.home", "/usr/lib/jvm/java-8-openjdk-amd64/jre"); 
            java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("user.home", "/home/pavel"); 
                                        java.lang.System.setProperty("user.dir", "/home/pavel/Projects/Luna/workspace-luna-git-2017/CMemvit"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("awt.toolkit", "sun.awt.X11.XToolkit"); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("file.separator", "/"); 
        java.lang.System.setProperty("java.awt.graphicsenv", "sun.awt.X11GraphicsEnvironment"); 
    java.lang.System.setProperty("java.awt.printerjob", "sun.print.PSPrinterJob"); 
    java.lang.System.setProperty("java.class.path", "/tmp/EvoSuite_pathingJar2925315322346140985.jar"); 
    java.lang.System.setProperty("java.class.version", "52.0"); 
        java.lang.System.setProperty("java.endorsed.dirs", "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed"); 
    java.lang.System.setProperty("java.ext.dirs", "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext"); 
    java.lang.System.setProperty("java.library.path", "lib"); 
    java.lang.System.setProperty("java.runtime.name", "OpenJDK Runtime Environment"); 
    java.lang.System.setProperty("java.runtime.version", "1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13"); 
    java.lang.System.setProperty("java.specification.name", "Java Platform API Specification"); 
    java.lang.System.setProperty("java.specification.vendor", "Oracle Corporation"); 
        java.lang.System.setProperty("java.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vendor.url", "http://java.oracle.com/"); 
    java.lang.System.setProperty("java.version", "1.8.0_121"); 
    java.lang.System.setProperty("java.vm.info", "mixed mode"); 
    java.lang.System.setProperty("java.vm.name", "OpenJDK 64-Bit Server VM"); 
    java.lang.System.setProperty("java.vm.specification.name", "Java Virtual Machine Specification"); 
    java.lang.System.setProperty("java.vm.specification.vendor", "Oracle Corporation"); 
    java.lang.System.setProperty("java.vm.specification.version", "1.8"); 
    java.lang.System.setProperty("java.vm.version", "25.121-b13"); 
    java.lang.System.setProperty("line.separator", "\n"); 
    java.lang.System.setProperty("os.arch", "amd64"); 
    java.lang.System.setProperty("os.name", "Linux"); 
    java.lang.System.setProperty("os.version", "4.10.0-041000-generic"); 
    java.lang.System.setProperty("path.separator", ":"); 
    java.lang.System.setProperty("user.country", "RU"); 
    java.lang.System.setProperty("user.language", "ru"); 
    java.lang.System.setProperty("user.name", "pavel"); 
    java.lang.System.setProperty("user.timezone", "Europe/Moscow"); 
                                                                    java.lang.System.setProperty("sun.arch.data.model", "64"); 
                                                                                          }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Controller_ESTest_scaffolding.class.getClassLoader() ,
      "org.eclipse.core.internal.registry.KeyedElement",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIBreakpointManagement3",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIBreakpointManagement2",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIAddressToSource",
      "org.eclipse.core.internal.registry.RegistryIndexElement",
      "org.eclipse.swt.internal.gtk.GdkEventKey",
      "org.eclipse.osgi.util.NLS$MessagesProperties",
      "org.eclipse.swt.internal.Callback",
      "org.eclipse.swt.widgets.Dialog",
      "org.json.JSONException",
      "org.eclipse.swt.widgets.Composite",
      "org.osgi.framework.BundleReference",
      "org.eclipse.osgi.internal.util.SupplementDebug",
      "org.eclipse.core.internal.resources.FileState",
      "org.eclipse.swt.graphics.Cursor",
      "org.eclipse.osgi.service.debug.DebugOptions",
      "org.eclipse.cdt.debug.mi.core.MIPlugin",
      "org.eclipse.cdt.debug.mi.core.command.MIInfoSharedLibrary",
      "org.eclipse.cdt.debug.mi.core.RxThread",
      "org.eclipse.swt.widgets.ToolItem",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBExit",
      "org.eclipse.cdt.debug.mi.core.command.CLIInfoSignals",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.PointerValue",
      "org.eclipse.ui.IWorkingSet",
      "org.eclipse.jface.operation.IRunnableContext",
      "org.eclipse.cdt.debug.core.cdi.ICDISessionConfiguration",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakAfter",
      "org.eclipse.core.internal.registry.ThirdLevelConfigurationElementHandle",
      "org.eclipse.ui.IPageService",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.IntegralValue",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIVariable",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIGlobalVariableDescriptor",
      "org.eclipse.swt.events.PaintListener",
      "org.eclipse.equinox.log.LogFilter",
      "org.eclipse.core.resources.ResourcesPlugin",
      "ru.innopolis.lips.memvit.utils.DataExtractor",
      "org.eclipse.core.runtime.ListenerList",
      "org.eclipse.cdt.debug.mi.core.cdi.Session",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Register",
      "org.eclipse.ui.IWorkbenchPart",
      "org.eclipse.swt.widgets.EventTable",
      "org.eclipse.cdt.debug.core.cdi.ICDIEventManager",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIExecuteMoveInstructionPointer",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakInsert",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDILongValue",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIExpression",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIValue",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.IntValue",
      "org.eclipse.cdt.debug.mi.core.event.MIBreakpointCreatedEvent",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBSetBreakpointPending",
      "org.eclipse.core.runtime.Plugin",
      "org.eclipse.jface.resource.ImageDescriptor",
      "org.eclipse.ui.internal.registry.WorkingSetDescriptor",
      "org.eclipse.swt.events.ModifyListener",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIFloatValue",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.FunctionValue",
      "ru.innopolis.lips.memvit.Activator",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakDelete",
      "org.eclipse.ui.WorkbenchException",
      "org.osgi.framework.BundleActivator",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.ArrayValue",
      "org.eclipse.jface.action.IAction",
      "org.eclipse.swt.widgets.TableColumn",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIWatchpoint2",
      "org.eclipse.debug.core.ILaunchConfiguration",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIBreakpoint",
      "org.eclipse.swt.events.PaintEvent",
      "org.eclipse.core.runtime.IStatus",
      "org.eclipse.osgi.service.datalocation.Location",
      "org.eclipse.jface.resource.DeviceResourceDescriptor",
      "org.eclipse.cdt.debug.mi.core.event.MIInferiorCreatedEvent",
      "org.eclipse.core.runtime.IBundleGroupProvider",
      "org.eclipse.core.runtime.IExtensionPoint",
      "org.eclipse.swt.widgets.Widget",
      "org.eclipse.core.runtime.IAdaptable",
      "org.eclipse.cdt.debug.mi.core.MIException",
      "org.eclipse.ui.internal.AbstractWorkingSet",
      "org.eclipse.cdt.debug.mi.core.command.MIInterpreterExec",
      "org.eclipse.cdt.debug.core.cdi.model.ICDILocalVariableDescriptor",
      "org.eclipse.core.runtime.IProgressMonitor",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.LongValue",
      "org.eclipse.cdt.debug.core.cdi.CDIException",
      "org.osgi.service.log.LogListener",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.DerivedValue",
      "org.eclipse.ui.internal.WorkingSet",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBShowPrompt",
      "org.eclipse.cdt.debug.core.cdi.model.ICDILocalVariable",
      "org.eclipse.cdt.debug.mi.core.command.CLIInfoSharedLibrary",
      "org.eclipse.core.internal.registry.ExtensionPoint",
      "org.eclipse.core.runtime.PlatformObject",
      "org.eclipse.cdt.debug.mi.core.command.MITargetSelect",
      "org.eclipse.core.runtime.IExecutableExtension",
      "org.eclipse.cdt.debug.mi.core.cdi.MemoryManager",
      "org.eclipse.cdt.debug.mi.core.command.CLICommand",
      "org.eclipse.core.internal.utils.UniversalUniqueIdentifier",
      "org.eclipse.swt.graphics.Drawable",
      "org.eclipse.swt.widgets.Combo",
      "org.eclipse.swt.widgets.Layout",
      "org.eclipse.ui.internal.WorkbenchMessages",
      "org.eclipse.cdt.debug.mi.core.command.MIVarUpdate",
      "org.eclipse.ui.IWorkbenchSite",
      "org.eclipse.ui.IPersistableElement",
      "org.eclipse.cdt.debug.core.cdi.ICDIAddressLocation",
      "org.eclipse.swt.internal.gtk.GtkAllocation",
      "org.eclipse.core.runtime.InvalidRegistryObjectException",
      "org.eclipse.swt.widgets.CoolItem",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIFloatingPointValue",
      "org.eclipse.cdt.debug.core.cdi.ICDIFileLocation",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIThreadStorageDescriptor",
      "org.eclipse.ui.internal.DragHandle",
      "org.eclipse.swt.events.HelpListener",
      "org.eclipse.cdt.debug.mi.core.command.MIVarListChildren",
      "org.eclipse.cdt.debug.mi.core.command.MIVarInfoExpression",
      "org.eclipse.cdt.debug.mi.core.cdi.SessionObject",
      "org.eclipse.cdt.debug.mi.core.cdi.LineLocation",
      "org.eclipse.core.runtime.CoreException",
      "org.eclipse.cdt.debug.mi.core.command.MICommand",
      "org.eclipse.cdt.debug.mi.core.cdi.SourceManager",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.WCharValue",
      "org.eclipse.ui.PartInitException",
      "org.eclipse.core.runtime.AssertionFailedException",
      "org.eclipse.ui.services.IServiceLocator",
      "org.eclipse.cdt.debug.core.cdi.model.ICDISignalManagement",
      "org.eclipse.ui.IPluginContribution",
      "org.eclipse.cdt.debug.mi.core.event.MIBreakpointChangedEvent",
      "org.eclipse.cdt.debug.core.cdi.ICDIFunctionLocation",
      "org.eclipse.jface.action.Action$1",
      "org.eclipse.cdt.debug.mi.core.GDBTypeParser$GDBDerivedType",
      "org.eclipse.core.runtime.Status",
      "org.eclipse.cdt.debug.mi.core.command.CLIHandle",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIVariableDescriptor",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Variable",
      "org.eclipse.cdt.debug.mi.core.command.Command",
      "org.eclipse.core.internal.runtime.CommonMessages",
      "org.eclipse.cdt.debug.mi.core.cdi.Condition",
      "org.eclipse.cdt.debug.core.cdi.ICDILineLocation",
      "org.eclipse.cdt.debug.mi.core.output.MIParser",
      "org.eclipse.cdt.debug.mi.core.command.MIVarDelete",
      "org.eclipse.swt.events.SelectionListener",
      "org.eclipse.cdt.debug.mi.core.output.MIBreakpoint",
      "org.eclipse.cdt.debug.mi.core.cdi.RegisterManager",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIIntegralValue",
      "org.eclipse.cdt.debug.mi.core.command.MIStackListLocals",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIExecuteStep",
      "org.eclipse.cdt.debug.mi.core.cdi.model.AddressLocation",
      "org.eclipse.cdt.debug.mi.core.command.MIDataEvaluateExpression",
      "org.eclipse.core.internal.registry.KeyedHashSet",
      "org.eclipse.swt.graphics.Font",
      "org.eclipse.swt.graphics.Resource",
      "org.eclipse.swt.widgets.TableItem",
      "org.eclipse.swt.widgets.Shell",
      "org.eclipse.cdt.debug.mi.core.event.MICreatedEvent",
      "org.eclipse.core.runtime.ISafeRunnable",
      "org.eclipse.cdt.debug.core.cdi.model.ICDITarget",
      "org.eclipse.ui.IViewSite",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIThreadStorage",
      "org.eclipse.swt.widgets.Synchronizer",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.DoubleValue",
      "org.eclipse.cdt.debug.mi.core.cdi.SignalManager",
      "org.eclipse.cdt.debug.mi.core.GDBTypeParser$GDBType",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Value",
      "org.eclipse.swt.graphics.Color",
      "org.eclipse.cdt.debug.mi.core.command.MIExecFinish",
      "org.eclipse.core.runtime.Platform",
      "org.eclipse.cdt.debug.mi.core.output.MIOutput",
      "org.eclipse.cdt.debug.mi.core.output.MIVar",
      "org.eclipse.core.runtime.IAdapterManager",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIExceptionpoint",
      "org.eclipse.cdt.debug.mi.core.cdi.model.FunctionLocation",
      "org.eclipse.cdt.debug.mi.core.cdi.VariableManager",
      "org.eclipse.cdt.debug.mi.core.command.CLITargetAttach",
      "org.eclipse.swt.events.TypedEvent",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.CharValue",
      "org.eclipse.cdt.debug.mi.core.command.MIExecReturn",
      "org.eclipse.ui.IPropertyListener",
      "org.eclipse.swt.events.VerifyListener",
      "org.eclipse.cdt.debug.core.cdi.event.ICDIEventListener",
      "org.eclipse.ui.IViewPart",
      "org.eclipse.swt.widgets.DateTime",
      "org.eclipse.swt.widgets.Decorations",
      "org.eclipse.cdt.debug.mi.core.MISession",
      "org.osgi.framework.BundleException",
      "org.eclipse.core.runtime.IExtension",
      "org.osgi.framework.InvalidSyntaxException",
      "org.eclipse.cdt.debug.mi.core.output.MIInfo",
      "org.eclipse.core.internal.registry.ReferenceMap",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIFunctionBreakpoint",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIShortValue",
      "org.eclipse.swt.widgets.Display",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Argument",
      "org.eclipse.cdt.debug.mi.core.SessionProcess",
      "org.eclipse.cdt.debug.mi.core.cdi.model.FunctionBreakpoint",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIAddressBreakpoint",
      "org.eclipse.core.runtime.Preferences",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBSetStopOnSolibEvents",
      "org.eclipse.jface.action.LegacyActionTools",
      "org.eclipse.cdt.debug.mi.core.command.factories.CommandFactoryManager",
      "org.eclipse.core.resources.IEncodedStorage",
      "org.eclipse.cdt.debug.mi.core.command.MIStackListFrames",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIStructValue",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.FloatValue",
      "ru.innopolis.lips.memvit.controller.DebugEventsListener",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBSetSolibSearchPath",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIRegister",
      "org.eclipse.cdt.debug.core.cdi.model.ICDISignal",
      "org.eclipse.swt.internal.gtk.GdkRectangle",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIDoubleValue",
      "org.eclipse.cdt.debug.mi.core.Queue",
      "org.eclipse.cdt.debug.mi.core.cdi.model.AddressBreakpoint",
      "org.eclipse.cdt.debug.core.cdi.event.ICDIEvent",
      "org.eclipse.swt.widgets.Event",
      "org.eclipse.ui.part.IWorkbenchPartOrientation",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Watchpoint",
      "ru.innopolis.lips.memvit.view.View",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Target",
      "org.eclipse.core.resources.IWorkspace",
      "org.eclipse.swt.internal.gtk.GtkRequisition",
      "org.eclipse.cdt.debug.core.cdi.ICDISessionObject",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakWatch",
      "org.eclipse.cdt.debug.core.cdi.ICDICondition",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIExpressionManagement",
      "org.eclipse.cdt.debug.mi.core.cdi.BreakpointManager",
      "org.eclipse.core.internal.registry.ExtensionRegistry",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBShow",
      "org.eclipse.cdt.debug.mi.core.command.MIInterpreterExecConsole",
      "org.eclipse.swt.widgets.TreeItem",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.ShortValue",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIExecuteStepReturn",
      "org.eclipse.cdt.debug.mi.core.cdi.model.LocalVariable",
      "org.eclipse.swt.widgets.Menu",
      "org.eclipse.ui.IWorkingSetManager",
      "org.eclipse.core.runtime.IPluginDescriptor",
      "org.eclipse.swt.internal.C",
      "org.eclipse.core.internal.registry.RegistryObjectManager",
      "org.eclipse.ui.IWorkbenchPartSite",
      "org.eclipse.cdt.debug.mi.core.event.MIEvent",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakDisable",
      "org.eclipse.ui.IWorkbenchWindow",
      "org.eclipse.core.internal.registry.ExtensionPointHandle",
      "org.eclipse.jface.action.AbstractAction",
      "org.eclipse.cdt.debug.mi.core.cdi.SharedLibraryManager",
      "org.eclipse.cdt.debug.mi.core.cdi.MI2CDIException",
      "org.eclipse.swt.graphics.Point",
      "org.eclipse.cdt.debug.mi.core.command.MIDataListChangedRegisters",
      "org.eclipse.swt.widgets.Scrollable",
      "org.eclipse.cdt.debug.mi.core.cdi.ExpressionManager",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakCondition",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIPointerValue",
      "org.eclipse.cdt.debug.mi.core.cdi.Manager",
      "org.eclipse.cdt.debug.mi.core.command.MIVarSetFormat",
      "org.eclipse.swt.internal.gtk.GdkEvent",
      "org.eclipse.swt.widgets.TreeColumn",
      "org.eclipse.swt.internal.gtk.GtkBorder",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIStackFrame",
      "org.eclipse.core.internal.utils.Messages",
      "org.eclipse.ui.part.WorkbenchPart",
      "org.eclipse.cdt.debug.mi.core.command.CLIPType",
      "org.eclipse.core.runtime.ILog",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIEnumValue",
      "org.eclipse.swt.graphics.Device",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDILongLongValue",
      "org.eclipse.cdt.debug.mi.core.MIProcess",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDICharValue",
      "org.eclipse.cdt.debug.mi.core.cdi.model.VariableDescriptor",
      "org.eclipse.core.internal.registry.Extension",
      "org.eclipse.cdt.debug.mi.core.command.CLIExecAbort",
      "org.eclipse.swt.events.SegmentListener",
      "org.eclipse.cdt.debug.mi.core.cdi.RegisterManager$ShadowRegister",
      "org.eclipse.cdt.debug.mi.core.cdi.model.ThreadStorageDescriptor",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.StructValue",
      "org.eclipse.core.internal.registry.HashtableOfStringAndInt",
      "org.eclipse.jface.window.IShellProvider",
      "org.eclipse.cdt.debug.mi.core.command.CLICatch",
      "org.eclipse.swt.internal.SerializableCompatibility",
      "ru.innopolis.lips.memvit.model.StateStorage",
      "org.eclipse.ui.internal.util.Util",
      "ru.innopolis.lips.memvit.controller.Controller",
      "ru.innopolis.lips.memvit.utils.JsonUtils",
      "ru.innopolis.lips.memvit.model.State",
      "org.eclipse.core.internal.registry.BaseExtensionPointHandle",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIDerivedValue",
      "org.eclipse.swt.widgets.TaskBar",
      "org.eclipse.core.internal.registry.ReferenceMap$IEntry",
      "org.eclipse.jface.util.IPropertyChangeListener",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIWCharValue",
      "org.eclipse.ui.IMemento",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIBoolValue",
      "org.eclipse.cdt.debug.mi.core.event.MIVarDeletedEvent",
      "org.eclipse.ui.IPersistable",
      "org.eclipse.swt.internal.Platform",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.AggregateValue",
      "org.eclipse.jface.action.IMenuCreator",
      "org.eclipse.core.internal.runtime.Messages",
      "org.eclipse.cdt.debug.core.cdi.ICDILocation",
      "org.eclipse.swt.events.DisposeListener",
      "org.eclipse.swt.widgets.CoolBar",
      "org.eclipse.swt.widgets.ToolBar",
      "org.eclipse.cdt.debug.mi.core.command.MIVarAssign",
      "org.eclipse.core.internal.registry.Handle",
      "org.eclipse.cdt.debug.core.cdi.ICDISession",
      "org.eclipse.swt.SWTError",
      "ru.innopolis.lips.memvit.controller.Controller$ThreadUpdateChecker",
      "org.eclipse.core.runtime.IExtensionRegistry",
      "org.eclipse.cdt.debug.mi.core.MIInferior",
      "org.eclipse.cdt.debug.mi.core.cdi.model.CObject",
      "org.eclipse.core.internal.registry.ConfigurationElementHandle",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.ReferenceValue",
      "org.eclipse.core.resources.IFileState",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIIntValue",
      "org.eclipse.swt.internal.gtk.GdkRGBA",
      "org.eclipse.swt.widgets.Caret",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIThreadGroup",
      "org.eclipse.cdt.debug.mi.core.command.MIStackSelectFrame",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIType",
      "org.eclipse.core.internal.runtime.DataArea",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIEventBreakpoint",
      "org.eclipse.osgi.util.NLS$1",
      "org.eclipse.cdt.debug.mi.core.cdi.model.StackFrame",
      "org.eclipse.osgi.util.NLS$2",
      "org.eclipse.swt.graphics.Image",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Thread",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBShowSolibSearchPath",
      "org.eclipse.swt.graphics.DeviceData",
      "org.eclipse.cdt.debug.mi.core.cdi.model.ArgumentDescriptor",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIWatchpoint",
      "org.eclipse.cdt.debug.mi.core.cdi.model.GlobalVariable",
      "org.eclipse.swt.events.TreeListener",
      "org.eclipse.core.runtime.IRegistryChangeListener",
      "org.eclipse.core.internal.registry.IObjectManager",
      "org.eclipse.swt.widgets.Monitor",
      "org.eclipse.jface.action.Action",
      "org.eclipse.core.internal.registry.ConfigurationElement",
      "org.eclipse.ui.IWorkbenchPart3",
      "org.eclipse.ui.IWorkbenchPart2",
      "org.eclipse.swt.internal.Lock",
      "org.eclipse.core.runtime.spi.IDynamicExtensionRegistry",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIArrayValue",
      "org.eclipse.swt.internal.SWTEventObject",
      "org.eclipse.cdt.debug.mi.core.command.MIVarInfoType",
      "org.eclipse.cdt.debug.mi.core.output.MIGDBShowInfo",
      "org.eclipse.core.internal.resources.ResourceException",
      "org.eclipse.swt.internal.gtk.GdkColor",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIMemoryBlockManagement",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.FloatingPointValue",
      "org.eclipse.cdt.debug.mi.core.cdi.ProcessManager",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Breakpoint",
      "org.eclipse.swt.internal.gtk.GdkEventMotion",
      "org.eclipse.core.internal.registry.ExtensionHandle",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIObject",
      "org.eclipse.cdt.debug.mi.core.output.MIOOBRecord",
      "org.eclipse.core.resources.IStorage",
      "org.eclipse.cdt.debug.core.cdi.model.ICDISharedLibraryManagement",
      "org.eclipse.core.internal.runtime.LocalizationUtils",
      "org.eclipse.swt.widgets.Tray",
      "org.eclipse.swt.internal.gtk.GtkAdjustment",
      "org.eclipse.cdt.debug.mi.core.cdi.Location",
      "org.eclipse.swt.accessibility.AccessibleListener",
      "org.eclipse.cdt.debug.mi.core.command.CommandFactory",
      "org.eclipse.cdt.debug.mi.core.cdi.model.LineBreakpoint",
      "org.eclipse.core.runtime.Assert",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIFunctionValue",
      "org.eclipse.swt.events.MouseEvent",
      "org.eclipse.swt.widgets.Item",
      "org.eclipse.cdt.debug.mi.core.event.MIDestroyedEvent",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIThread",
      "org.eclipse.cdt.debug.mi.core.command.MIDataListRegisterNames",
      "org.eclipse.ui.part.ViewPart",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakList",
      "ru.innopolis.lips.memvit.model.Model",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIGlobalVariable",
      "org.eclipse.cdt.debug.mi.core.command.MIVarCreate",
      "org.eclipse.cdt.debug.core.cdi.model.ICDILineBreakpoint",
      "org.eclipse.cdt.debug.mi.core.cdi.model.GlobalVariableDescriptor",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBSet",
      "org.eclipse.core.internal.registry.BaseExtensionHandle",
      "org.eclipse.swt.widgets.Listener",
      "org.eclipse.core.runtime.IConfigurationElement",
      "org.eclipse.ui.plugin.AbstractUIPlugin",
      "org.eclipse.cdt.debug.mi.core.command.MIThreadSelect",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIRegisterDescriptor",
      "org.eclipse.cdt.debug.mi.core.command.MIStackInfoDepth",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIArgumentDescriptor",
      "org.eclipse.cdt.debug.core.cdi.model.ICDILocationBreakpoint",
      "org.eclipse.cdt.debug.mi.core.cdi.model.LocalVariableDescriptor",
      "org.eclipse.cdt.debug.mi.core.cdi.model.ThreadStorage",
      "org.eclipse.swt.internal.Converter",
      "org.eclipse.swt.graphics.GCData",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIBreakpoint2",
      "org.eclipse.core.commands.common.EventManager",
      "org.eclipse.swt.internal.Library",
      "org.eclipse.cdt.debug.core.cdi.model.ICDISuspend",
      "org.eclipse.cdt.debug.mi.core.cdi.model.EventBreakpoint",
      "org.eclipse.cdt.debug.mi.core.command.MIGDBSetAutoSolib",
      "org.eclipse.cdt.debug.mi.core.command.MIBreakEnable",
      "org.eclipse.cdt.debug.core.cdi.ICDILocator",
      "org.eclipse.swt.layout.GridLayout",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.EnumValue",
      "ru.innopolis.lips.memvit.view.BrowserView",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIAggregateValue",
      "org.eclipse.swt.graphics.GC",
      "org.eclipse.core.internal.registry.Contribution",
      "org.eclipse.core.runtime.IPath",
      "org.eclipse.core.runtime.IContributor",
      "org.osgi.framework.Bundle",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIArgument",
      "org.eclipse.osgi.util.NLS",
      "org.eclipse.osgi.service.resolver.PlatformAdmin",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIMemoryBlock",
      "org.eclipse.cdt.debug.mi.core.CommandQueue",
      "org.eclipse.core.internal.runtime.InternalPlatform",
      "org.eclipse.cdt.debug.core.cdi.model.ICDISourceManagement",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIExecuteResume",
      "org.eclipse.cdt.debug.core.cdi.model.ICDIBreakpointManagement",
      "org.osgi.framework.BundleContext",
      "org.eclipse.swt.widgets.Tree",
      "org.eclipse.swt.internal.SWTEventListener",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.BoolValue",
      "org.eclipse.swt.graphics.Rectangle",
      "org.eclipse.swt.widgets.Table",
      "org.eclipse.cdt.debug.mi.core.command.CLISharedLibrary",
      "org.eclipse.core.internal.registry.RegistryProperties",
      "org.eclipse.cdt.debug.mi.core.IMITTY",
      "org.eclipse.core.internal.registry.RegistryObject",
      "org.eclipse.cdt.debug.core.cdi.model.type.ICDIReferenceValue",
      "org.eclipse.swt.widgets.Canvas",
      "org.eclipse.swt.accessibility.AccessibleControlListener",
      "org.eclipse.cdt.debug.mi.core.cdi.model.LocationBreakpoint",
      "org.eclipse.cdt.debug.mi.core.event.MIChangedEvent",
      "org.eclipse.cdt.debug.mi.core.cdi.model.RegisterDescriptor",
      "org.eclipse.cdt.debug.mi.core.command.MIVarShowAttributes",
      "org.eclipse.cdt.debug.mi.core.GDBTypeParser",
      "org.eclipse.cdt.debug.mi.core.cdi.model.type.LongLongValue",
      "org.eclipse.swt.layout.RowLayout",
      "org.eclipse.swt.graphics.FontData",
      "org.eclipse.core.runtime.spi.RegistryContributor",
      "org.eclipse.swt.widgets.ScrollBar",
      "org.eclipse.core.runtime.ILogListener",
      "org.eclipse.swt.widgets.Control",
      "org.eclipse.cdt.debug.mi.core.command.MIStackListArguments"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Controller_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.eclipse.cdt.debug.mi.core.MISession",
      "org.eclipse.swt.graphics.Device",
      "org.eclipse.swt.internal.Converter",
      "org.eclipse.swt.widgets.Display",
      "org.eclipse.swt.widgets.Widget",
      "org.eclipse.swt.widgets.Composite",
      "org.eclipse.ui.internal.DragHandle",
      "org.eclipse.swt.internal.Platform",
      "org.eclipse.swt.internal.Library",
      "org.eclipse.swt.internal.C",
      "org.eclipse.cdt.debug.mi.core.cdi.Session",
      "org.eclipse.cdt.debug.mi.core.cdi.ProcessManager",
      "org.eclipse.cdt.debug.mi.core.cdi.BreakpointManager",
      "org.eclipse.cdt.debug.mi.core.cdi.ExpressionManager",
      "org.eclipse.cdt.debug.mi.core.cdi.VariableManager",
      "org.eclipse.cdt.debug.mi.core.GDBTypeParser",
      "org.eclipse.core.runtime.Plugin",
      "org.eclipse.osgi.util.NLS",
      "org.eclipse.osgi.util.NLS$MessagesProperties",
      "org.eclipse.osgi.internal.util.SupplementDebug",
      "org.eclipse.core.internal.runtime.Messages",
      "org.eclipse.core.runtime.Platform",
      "org.eclipse.core.internal.runtime.InternalPlatform",
      "org.eclipse.cdt.debug.mi.core.MIPlugin",
      "org.eclipse.core.commands.common.EventManager",
      "org.eclipse.core.runtime.ListenerList",
      "org.eclipse.core.internal.registry.RegistryObjectManager",
      "org.eclipse.core.internal.registry.KeyedHashSet",
      "org.eclipse.core.internal.registry.HashtableOfStringAndInt",
      "org.eclipse.core.internal.registry.RegistryProperties",
      "org.eclipse.core.internal.registry.ReferenceMap",
      "org.eclipse.core.internal.registry.ConfigurationElementHandle",
      "org.eclipse.swt.internal.SWTEventObject",
      "org.eclipse.swt.events.TypedEvent",
      "org.eclipse.swt.events.MouseEvent",
      "org.eclipse.swt.widgets.DateTime",
      "org.eclipse.cdt.debug.mi.core.cdi.model.Thread",
      "org.eclipse.ui.internal.WorkbenchMessages",
      "org.eclipse.core.runtime.CoreException",
      "org.eclipse.ui.WorkbenchException",
      "org.eclipse.core.internal.runtime.CommonMessages",
      "org.eclipse.core.runtime.Status",
      "org.eclipse.jface.action.Action",
      "org.eclipse.jface.action.LegacyActionTools",
      "org.eclipse.ui.internal.AbstractWorkingSet",
      "org.eclipse.ui.internal.util.Util",
      "org.eclipse.ui.internal.WorkingSet",
      "org.eclipse.core.runtime.AssertionFailedException",
      "org.eclipse.core.runtime.InvalidRegistryObjectException",
      "org.eclipse.swt.widgets.Tree",
      "org.eclipse.core.internal.registry.ExtensionHandle",
      "org.eclipse.swt.widgets.Table",
      "org.eclipse.core.resources.ResourcesPlugin",
      "org.eclipse.core.internal.utils.Messages",
      "org.eclipse.core.internal.resources.FileState",
      "org.eclipse.swt.widgets.Combo",
      "org.eclipse.swt.widgets.CoolBar",
      "org.eclipse.swt.internal.Callback",
      "org.eclipse.swt.widgets.ToolBar"
    );
  }
}
