/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 20:10:28 GMT 2017
 */

package ru.innopolis.lips.memvit.controller;

import org.junit.Test;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

import ru.innopolis.lips.memvit.controller.Controller;
import ru.innopolis.lips.memvit.controller.DebugEventsListenerRegistrator;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DebugEventsListenerRegistrator_ESTest extends DebugEventsListenerRegistrator_ESTest_scaffolding {

  @SuppressWarnings("unused")
@Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DebugEventsListenerRegistrator debugEventsListenerRegistrator0 = null;
      try {
        debugEventsListenerRegistrator0 = new DebugEventsListenerRegistrator((Controller) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/eclipse/core/runtime/preferences/IScopeContext
         //
         assertThrownBy("ru.innopolis.lips.memvit.controller.DebugEventsListenerRegistrator", e);
      }
  }
}
